[package]
name = "boatbomber/cullthrottle"
description = "Manage effects for tens of thousands of objects, performantly."
version = "0.1.0-rc.4"
license = "MPL 2.0"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = [
    "dist/src",
    "dist/src/**",
    "wally.toml",
    "wally.lock",
    "build.project.json",
]
exclude = ["**", "dist/src/__tests__", "dist/src/jest.config.luau"]

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
